---
- hosts: challs
  gather_facts: no

  tasks:
    - name: Get current user name
      command: whoami
      changed_when: false
      become: no
      register: whoami

    - name: Update repositories
      apt:
        update_cache: yes
      become: yes

    - name: Install usefull packages
      apt:
        pkg:
          - vim
          - git
          - unzip
      become: yes

    - name: Install docker
      apt:
        pkg:
          - docker.io
          - docker-compose
      become: yes
    
    - name: Enable and start docker
      systemd:
        name: docker
        state: started
        enabled: yes
      become: yes
    
    - name: Add docker group to the user '{{ whoami.stdout }}'
      user:
        name: "{{ whoami.stdout }}"
        groups: docker
        append: yes
      become: yes

    - name: Copy github.key
      copy:
        src: "files/github.key"
        dest: "/home/{{ whoami.stdout }}/github.key"
        owner: "{{ whoami.stdout }}"
        group: "{{ whoami.stdout }}"
        mode: "0600"

    - name: Clone HeroCTF challenges
      git:
        repo: "git@github.com:HeroCTF/HeroCTF_v3.git"
        dest: "/home/{{ whoami.stdout }}/challenges"
        accept_hostkey: yes
        key_file: "/home/{{ whoami.stdout }}/github.key"
        force: yes
